package com.aikodasistani.aikodasistani.projectgen

import android.net.Uri

/**
 * Enterprise-Grade AI Project Generator - Domain Models
 * 
 * These models represent the core data structures for the provider-agnostic,
 * dynamic project scaffolding engine.
 * 
 * Key Design Principles:
 * - No provider-specific logic
 * - No model names hardcoded
 * - Fully dynamic and extensible
 * - Clean Architecture compliant
 */

/**
 * Represents a complete project structure generated by AI.
 * Contains the root directory name and all files within the project.
 */
data class ProjectStructure(
    val root: String,
    val files: List<ProjectFile>
) {
    val totalFiles: Int get() = files.size
    val totalSize: Long get() = files.sumOf { it.content.length.toLong() }
}

/**
 * Represents a single file within the generated project.
 * Stores the relative path from project root and the file content.
 */
data class ProjectFile(
    val path: String,
    val content: String
) {
    /**
     * The file name without directory path
     */
    val fileName: String get() = path.substringAfterLast("/")
    
    /**
     * The file extension
     */
    val extension: String get() = fileName.substringAfterLast(".", "")
    
    /**
     * The directory path (without file name)
     */
    val directory: String get() = if (path.contains("/")) path.substringBeforeLast("/") else ""
    
    /**
     * Whether this is a directory entry (empty content and path ends with /)
     */
    val isDirectory: Boolean get() = path.endsWith("/") || content.isEmpty()
}

/**
 * Provider-agnostic identifier for an AI provider.
 * This comes from UI/ViewModel selection, not hardcoded values.
 */
data class ProviderIdentifier(
    val name: String,
    val baseUrl: String
)

/**
 * Provider option representing a capability variant.
 * NOT a model name - represents UI-driven configuration.
 */
data class ProviderOption(
    val id: String,
    val displayName: String
)

/**
 * Request for AI-driven project generation.
 */
data class AiProjectRequest(
    val provider: ProviderIdentifier,
    val option: ProviderOption,
    val prompt: String,
    val projectName: String
)

/**
 * Result of project generation operation.
 */
sealed class ProjectGenerationOutput {
    /**
     * Successful project generation.
     */
    data class Success(
        val projectName: String,
        val structure: ProjectStructure,
        val zipUri: Uri,
        val zipPath: String,
        val totalFiles: Int,
        val totalSize: Long,
        val generationTimeMs: Long
    ) : ProjectGenerationOutput()
    
    /**
     * Error during project generation.
     */
    data class Error(
        val errorType: ErrorType,
        val message: String,
        val details: String? = null,
        val recoverable: Boolean = false
    ) : ProjectGenerationOutput()
    
    /**
     * Types of errors that can occur during generation.
     */
    enum class ErrorType {
        PROVIDER_UNREACHABLE,
        EMPTY_AI_RESPONSE,
        MALFORMED_OUTPUT,
        FILE_SYSTEM_FAILURE,
        STORAGE_QUOTA_EXCEEDED,
        ZIP_CREATION_FAILURE,
        PARSE_FAILURE,
        UNKNOWN
    }
}

/**
 * Intermediate result from AI response before parsing.
 */
sealed class AiProviderResult {
    data class Success(val rawOutput: String) : AiProviderResult()
    data class Error(val message: String, val cause: Throwable? = null) : AiProviderResult()
}

/**
 * Result of parsing AI output.
 */
sealed class ParserResult {
    data class Success(val structure: ProjectStructure) : ParserResult()
    data class Error(val message: String, val rawOutput: String? = null) : ParserResult()
}

/**
 * Result of file writing operation.
 */
sealed class FileWriterResult {
    data class Success(val writtenFiles: Int, val outputDir: String) : FileWriterResult()
    data class Error(val message: String, val failedPath: String? = null) : FileWriterResult()
}

/**
 * Result of ZIP creation operation.
 */
sealed class ZipResult {
    data class Success(val zipUri: Uri, val zipPath: String, val sizeBytes: Long) : ZipResult()
    data class Error(val message: String) : ZipResult()
}
